Google fit gawen
ichnion/excavator pull request #41
Opened 2021-05-25 07:12 UTC by GawenMonnot

fixes #40

2021-05-25 07:20 UTC, chansuke commented on src/activities/google/google_fit_activity.rs
> +        //for elem in self.fit.iter() {
delete this comment out, thanks

2021-05-25 07:23 UTC, chansuke commented on src/activities/google/google_fit_activity.rs
> +       // }
And this line too

2021-05-25 08:52 UTC, chansuke commented on src/activities/google/google_fit_activity.rs
> +        //for elem in self.fit.iter() {
Thanks

2021-05-25 08:53 UTC, chansuke approved these changes
LGTM. Thanks

2021-05-25 13:41 UTC, chansuke requested changes
@GawenMonnot Sorry Gawen, can you format the code with this command
`cargo format --all`

2021-05-25 14:17 UTC, GawenMonnot commented
> @GawenMonnot Sorry Gawen, can you format the code with this command
> `cargo format --all`

@chansuke Do you mean `cargo fmt --all` ?

2021-05-26 16:50 UTC, GawenMonnot commented
> @GawenMonnot Sorry Gawen, can you format the code with this command
> `cargo fmt --all`

It should be done now.

2021-05-27 04:46 UTC, chansuke approved these changes
Everything is ready to merge. Thanks, Gawen!!!

2021-05-28 07:58 UTC, merged